//@version=5

// This indicator draws a ribbon of moving averages.
// GitHub: https://github.com/chingc/TradingView
// X: https://x.com/NeonNoodle22

indicator(title='Moving Average Ribbon', shorttitle='Ribbon', overlay=true)

// user settings
src = input.source(defval=close, title='Source')
maType = input.string(defval='EMA', title='이동평균 종류', options=['SMA', 'EMA', 'WMA', 'VWMA'])
show100 = input.bool(defval=true, title='MA 100')
show200 = input.bool(defval=true, title='MA 200')

// return a moving average of the given length using the selected type
ma(length) =>
    switch maType
        'SMA' => ta.sma(src, length)
        'EMA' => ta.ema(src, length)
        'WMA' => ta.wma(src, length)
        'VWMA' => ta.vwma(src, length)

ma20 = ma(20)
ma25 = ma(25)
ma30 = ma(30)
ma35 = ma(35)
ma40 = ma(40)
ma45 = ma(45)
ma50 = ma(50)

// draw moving averages
plot(series=ma20, title='MA 20', color=#FFFF0080)
plot(series=ma25, title='MA 25', color=#FFDF0080)
plot(series=ma30, title='MA 30', color=#FFBF0080)
plot(series=ma35, title='MA 35', color=#FF9F0080)
plot(series=ma40, title='MA 40', color=#FF7F0080)
plot(series=ma45, title='MA 45', color=#FF5F0080)
plot(series=ma50, title='MA 50', color=#FF3F0080)

ma100 = show100 ? ma(100) : na
ma200 = show200 ? ma(200) : na
p100 = plot(series=ma100, title='MA 100', color=#FF0000FF)
p200 = plot(series=ma200, title='MA 200', color=#800000FF)

// fill the area between ma100 and ma200
fill(plot1=p100, plot2=p200, color=ma100 > ma200 ? #4CAF5033 : #FF525233, title='MA Fill')
